remove install script; expect that these utils are already installed

diff --git a/common b/common
--- a/common
+++ b/common
@@ -4,7 +4,7 @@ docker_bin="/usr/bin/docker"
 [ -x "$docker_bin" ] || docker_bin="$(which docker | head -n1)" 
 if [ ! -x "$docker_bin" ] 
 then
-	echo "docker not found, please run install script" 1>&2
+	echo "docker not found in path" 1>&2
 	exit 1
 else
 	export docker_bin
@@ -15,7 +15,7 @@ compose_bin="/usr/local/bin/docker-compose"
 [ -x "$compose_bin" ] || compose_bin="$(which docker-compose | head -n1)" 
 if [ ! -x "$compose_bin" ] 
 then
-	echo "docker-compose not found, please run install script" 1>&2
+	echo "docker-compose not found in path" 1>&2
 	exit 1
 else
 	export compose_bin
